spring:
  profiles:
    active: @profile.active@
server:
  port: 8099
mybatis:
  type-aliases-package: com.xiaomi.xiaoai.servicefunc
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl