spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.108.233.3:6719/db_monitor?useUnicode=true&characterEncoding=utf8&characterSetResults=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&transformedBitIsBoolean=true
    username: db_monitor_staging
    password: db_monitor_staging
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
logging:
  config: classpath:logback-spring.xml